### ISSUE TITLE
@everyone does not get filtered

### ISSUE THREAD

**Issue by kb-1000** [Geek202/TomsServerUtils#7]
This is critical.
Please make the mod filter @ everyone mentions (for example by adding a zero width space between the @ and the everyone)
![image](https://user-images.githubusercontent.com/18211838/108609502-98dcda80-73ce-11eb-8b7c-32fb095183ce.png)

**Comment by Tom-The-Geek** [comment]
I should be able to fix this by sending an empty allowed mentions list as part of the webhook, rather than doing a (slightly) dirty hack

**Comment by kb-1000** [comment]
Being able to mention specific users would be nice though (so a normal mention). Probably not everyone wants that though, so having it be configurable would be good...

**Comment by Tom-The-Geek** [comment]
Yep! I'll look into this one in the morning, I might have a few modes like: No filtering, No @everyone (inserts thin space) and Only specific, where you can include a list of allowed mentions.

**Comment by Tom-The-Geek** [comment]
I've added a new config section that looks like this: (these are the default values)
![image](https://user-images.githubusercontent.com/23531706/108622434-b93d8100-7430-11eb-8030-c36ccb5cad99.png)
that I'll push when I've tested that it works

**Comment by Tom-The-Geek** [comment]
Seems to be working, will push and release soon!
![image](https://user-images.githubusercontent.com/23531706/108623316-446d4580-7436-11eb-9fda-664acf054485.png)
(@nothing is a role)
