### ISSUE TITLE
Stopping the server using /stop does not exit the process

### ISSUE THREAD

**Issue by kb-1000** [Geek202/TomsServerUtils#8]
Again, I suspect the websocket connection thread to be responsible for this.

**Comment by Tom-The-Geek** [comment]
Interesting, I thought I made sure it was properly shutdown. From a small amount of testing and from using it on a small server for friends, the server seems to hang for a few minutes after saving, but does eventually stop and exit cleanly, but I'll look into this

**Comment by kb-1000** [comment]
That it exits after a few minutes could very well be the case. I didn't wait for a long time, I just CTRL+C'd it after like 30 seconds.

**Comment by Tom-The-Geek** [comment]
Seems there's a few OkHttp threads left over in the time where it hangs, not sure if these are from JDA or the webhook library, as they both use OkHttp, but I'm going to take a look
![image](https://user-images.githubusercontent.com/23531706/108621995-053af680-742e-11eb-810a-eac4601376af.png)

**Comment by Tom-The-Geek** [comment]
Seems to be caused by HTTP 2 allowing connections to be kept alive. Disabling it on the `OkHttpClient` used by the webhooks seems to fix the issue
